defenseunicorns/uds-identity-config

src/realm.json
=> fix: add default ocsp for CACs

src/theme/login/login.ftl
Hardcoded url needs to be made dynamic for CAC registration
...
Fixes #18
=> fix: update link

src/sync.sh
"Graceful" erroring so that errors bubble up on the expected container.
N/A
=> fix: set -e on sync

src/sync.sh, src/theme/login/register.ftl
Fixes form id reference for the registration robot check
Fixes #
Relates to #
=> fix: register form id robot check

src/plugin/pom.xml, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/RegistrationValidation2Test.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/RegistrationValidationTest.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/RegistrationX509PasswordTest.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/UpdateX509Test.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/X509ToolsTest.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/utils/CommonConfig.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/utils/NewObjectProvider.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/utils/Utils.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/utils/ValidationUtils.java
=> renovate update kc to 24 and plugin test rework

src/theme/login/login.ftl, src/theme/login/resources/css/new-ui.css
Before we were unable to login using an identity provider ( google sso ). Now, if keycloak is configured with an identity provider there will be a section on the login page that allows for using that option.
Also fixed some indentation errors.
=> feat: modify theme to allow identity provider login

release-please-config.json
=> chore: please release config

bundles/uds-bundle.yaml, tasks.yaml
Temporarily integration test against main for Keycloak 24 upgrade
=> chore: update to integration test against main uds-core

.github/workflows/commitlint.yaml
=> ci: allow triggering ci in release pr

docs/CUSTOMIZE.md, src/realm.json, src/test/cypress/realm.json
Move identity sso from google oidc to google saml.
* updates to realm.json 's and docs
=> feat: google saml sso

docs/CUSTOMIZE.md, docs/INTEGRATION.md, docs/PLUGIN.md, docs/_index.md, docs/go.mod
Part of the move to setting up the integrated docs means formatting existing docs in a hugo style so that everything can be nice and pretty when pulled together. This is that.
=> feat: integrated docs setup

docs/CUSTOMIZE.md, docs/INTEGRATION.md, docs/PLUGIN.md, docs/_index.md
Small changes for meeting npm linting rules in the uds-docs repo. Mostly spacing and naming of code blocks.
=> chore: docs linting fixes

bundles/uds-bundle.yaml, tasks.yaml
pulled out the uds-core update from the main renovate branch since its currently stuck with keycloak 25 updates.
=> chore(deps): update uds core v0.23.0

src/realm.json
UDS-core incorporates Keycloak as the default IdP. The HNCD team has obtained an Elastic STIG directly from Elastic (not yet available on DoD website) that includes several rules relating to IdP settings, which in our case and UDS-core's case is Keycloak. Of the 66 rules related to Keycloak, we have identified 8 that can be easily incorporated into the UDS-core baseline. The proactive approach of incorporating these rules into the UDS-core baseline ensures the baseline is more secure and STIG compliant. This also decreases the amount of STIG remediation scripts that have to be run after deployment to make our mission deployments STIG compliant.
https://github.com/defenseunicorns/uds-identity-config/issues/140
=> feat: keycloak-STIGS

src/test/cypress/e2e/group-authz.cy.ts, src/test/cypress/e2e/login.cy.ts, src/test/cypress/e2e/registration.cy.ts, src/test/cypress/realm.json
keeping test realm in parity with default realm
Fixes #139
=> fix: update test realm to stig compliance

src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/Common.java, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/authentication/RequireGroupAuthenticator.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/authentication/RequireGroupAuthenticatorTest.java
When a user signs in, they are expected to be presented with terms and conditions regardless of which client they are on. Added some logic to check the client and ignore certain clients. 
Added new unit test for new if statement.
Fixes #173
=> fix: toc bug causing refresh issues

bundles/uds-bundle.yaml
Updates zarf refs to the new repo/org. Also updates to latest version.
N/A
=> chore: update zarf to new repo location, 0.37.0

docs/VERSION_UPGRADE.md
Adds upgrade notes for 0.5.1 to 0.5.2
=> chore: add upgrade notes for release

release-please-config.json
Adjust release config to not bump minor if features are added
=> chore: adjust versioning config

docs/reference/IAM/customization.md, docs/reference/IAM/integration.md, docs/reference/IAM/plugin.md, docs/reference/IAM/uds-identity-config-overview.md, docs/reference/IAM/upgrading-versions.md
This PR changes the docs structure to reflect the updated site architecture.
- All docs are served out of docs/reference (or possibly docs/troubleshooting if added)
- Remove unnecessary front matter as needed
N/A
=> chore(docs): update docs structure for new site

src/theme/account/resources/content.json
=> fix: react paths

docs/reference/UDS Core/IdAM/customization.md
=> chore(docs): update overrides for auth flows

docs/reference/UDS Core/IdAM/authentication-flows.md
Fixes a broken link.
Fixes https://github.com/defenseunicorns/uds-core/issues/1295
=> fix: broken docs link

docs/reference/UDS Core/IdAM/testing-deployment-customizations.md
=> chore: update doc for custom image

tasks.yaml
Revert our tasks to using the latest released version of core
=> chore: revert to latest core for tasks

src/theme/login/login.ftl
Remove "Test" from "New DoD PKI Detected" banner
=> fix: remove test from New DoD PKI Detected banner

.github/workflows/commitlint.yaml, docs/reference/UDS Core/IdAM/upgrading-versions.md
=> fix: update upgrading-versions.md

docs/reference/UDS Core/IdAM/upgrading-versions.md
Added steps to upgrade doc so that client credentials uds-operator works as expected when creating clients.
=> fix: upgrade docs

src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/clientpolicy/executor/UDSClientPolicyPermissionsExecutor.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/clientpolicy/executor/UDSClientPolicyPermissionsExecutorTest.java, src/test/cypress/e2e/client-credentials.cy.ts
This Pull Request changes the UDS Policy behavior, so that it throws an error on validation errors.
From the UDS Core perspective, this results in failing the Package. 
Fixes #464
=> feat: fail the UDS Core Package on validation errors

src/Dockerfile
Docker build fix (Chainguard changed image tags)
=> chore: docker image fix

docs/reference/UDS Core/IdAM/uds-identity-config-overview.md, docs/reference/UDS Core/IdAM/upgrading-versions.md
This Pull Request documents https://github.com/defenseunicorns/uds-core/pull/1537
Relates to https://github.com/defenseunicorns/uds-identity-config/issues/36
=> feat: keycloak FIPS docs

docs/reference/UDS Core/IdAM/customization.md
=> chore(docs): move branding customiation under theme section

docs/reference/UDS Core/IdAM/upgrading-versions.md
=> chore(docs): upgrade doc update

docs/dev/adr/0001-record-architecture-decisions.md, docs/dev/adr/0002-switching-required-ssl-to-none.adoc, docs/dev/adr/0002-switching-required-ssl-to-none.md, docs/reference/UDS Core/IdAM/upgrading-versions.md, src/realm.json
This Pull Request changes the "Required SSL" to "None"
Fixes https://github.com/defenseunicorns/uds-identity-config/issues/484
=> fix: require ssl set to none

src/theme/account/index.ftl, src/theme/account/resources/css/uds.css, src/theme/login/resources/css/uds.css, src/theme/login/template.ftl
Resolves issues with the mobile view of the new Keycloak theme.
=> fix: mobile responsiveness for kc theme

.github/workflows/commitlint.yaml
This Pull Request hardens the security configuration in Github Actions
Fixes https://github.com/defenseunicorns/uds-identity-config/issues/545
=> chore: security hardening

tasks.yaml
update new setup task name to be more unique and avoid clobbering uds-core tasks
=> fix: task naming

docs/reference/uds-core/idam/uds-identity-config-overview.md
fix broken link to image customizations
=> chore(docs): fix broken link to image customizations

src/test/cypress/e2e/tofu-client.cy.ts
This Pull Request fixes Cypress 15 tests.
=> fix: cypress 15 tests

src/realm.json
⚠️ This Pull Request depends on https://github.com/defenseunicorns/uds-core/pull/1925
This Pull Request disables the x509 subflows conditionally, see the screenshot:
Fixes https://github.com/defenseunicorns/uds-identity-config/issues/626
=> feat: x509 Authentication Flow control
