defenseunicorns/uds-identity-config

.github/workflows/test.yaml, .gitignore, README.md, tasks.yaml
Adds a docker build task for basic local dev/CI validation.
Also adds a `cacert` task that runs the image and gets the cacert in base64 encoded format for use in the istio gateway.
N/A
=> ci: add dev task for testing build + cacert

src/theme/login/register.ftl, src/theme/login/resources/css/new-ui.css, src/theme/login/template.ftl
While digging through some of the theme stuff, noticed there was still some extraneous references to p1 images and baby-yoda usecases. Removed those where necessary.
All changes i believe were copy and pasted from the existing idam-keycloak repo which was still still uilizing the baby-yoda realm and p1 theme by default. Cleanup to remove any confusion.
Tested locally by deploying uds-core and changing theme. Then registering a new user and logging in with user. In my testing the removal of css seemed to have no effect and searching through compiled css, there was no results for those css rules.
=> chore: cleanup misc baby-yoda references

.github/workflows/test.yaml, .gitignore, .vscode/settings.json, README.md, docs/CUSTOMIZE.md, renovate.json, src/Dockerfile, tasks.yaml, zarf.yaml
Occasionally, it may be useful to transport the identity-config image via zarf package. This PR Adds a simple `zarf.yaml` and corresponding UDS task for building it.
This will enable custom builds of this repository image to be more easily incorporated in UDS deployments, particularly in situations where the custom image may not be available at bundle create time.
=> feat: zarf file

src/realm.json
Add additional saml client scopes and protocol mappers. The specific mappers added here were discovered during gitlab integration but can be reused by other apps as needed. These mappers allow GitLab to display the user's full name and determine access based on the user's groups.
I also added descriptions to all "mapper" client scopes to explain what they do. The descriptions are visible in the client scopes list in the keycloak admin ui.
Relates to #https://github.com/defenseunicorns/uds-package-gitlab/issues/102
=> chore: add additional saml scopes and mappers for gitlab

docs/CUSTOMIZE.md, src/realm.json, src/test/cypress/e2e/login.cy.ts, src/test/cypress/e2e/registration.cy.ts, src/test/cypress/realm.json
We've been asked by more than a couple people to expose some additional keycloak realm settings. This is that.
Added env vars for the following:
* Required Actions
* Terms and Conditions
* One Time Password ( OTP )
* Email Verification
* Password Policy
* X509 OCSP Fail Open
In updating/testing the changes to the password policy, there was a couple changes necessary for the realms to handle the use of the `digits` in the `passwordPolicy`. While not strictly necessary a preemptive change to the cypress tests for user registration and login to update the passwords used was done as well.
The uds-core PR will need to be merged and uds-core released before CI jobs here will pass because of the dependency on the default env variables set in uds-core.
Relates to #32
=> fix: expose environment variables

src/sync.sh
Addresses an issue where existing files on disk are technically newer than files being copied in because of instances where initial installs have happened after the release of the `uds-identity-config` image.
=> fix: force sync to ensure copy occurs

bundles/uds-bundle.yaml, tasks.yaml
uds-core version renovate update is lumped in with keycloak 25 version changes..which isnt going anywhere soon. Separate PR to keep uds-core up to date.
Relates to #102
=> chore(deps): update uds-core version

README.md, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/X509Tools.java, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/authentication/Groups.java, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/authentication/RequireGroupAuthenticator.java, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/authentication/RequireGroupAuthenticatorFactory.java, src/plugin/src/main/resources/META-INF/services/org.keycloak.authentication.AuthenticatorFactory, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/authentication/RequireGroupAuthenticatonFactoryTest.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/authentication/RequireGroupAuthenticatorTest.java, src/realm.json, src/test/cypress/realm.json
* Adds authenticator that enforces client.attribute.groups membership
* Denies access if group does not exist
* Adds group authenticator to default realm configuration
* Adds group authenticator for IDP flow
* Unit Testing all the things
```yaml
apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
name: grafana
namespace: {{ .Release.Namespace }}
spec:
sso:
- name: Grafana Dashboard
clientId: uds-core-admin-grafana
redirectUris:
- "https://grafana.admin.{{ .Values.domain }}/login/generic_oauth"
groups:
anyOf:
- /UDS Core/Admin
```
This is related / has a sister PR in the [uds-core repo ](https://github.com/defenseunicorns/uds-core/pull/497)
=> feat: group authorization plugin

src/Dockerfile, src/theme/login/template.ftl
Login theme logo had some weird logic that is no longer being used. Removing the usecase of defining the login logo from the description that we override with our package definition. Now depends solely on the uds-logo in the identity config.
Maybe this removes the ability to override the default logo and that's something we want to enable, in which case we need to rework the use of description field.
Also noticed a small warning when building the uds-identity image dockerfile, fixed that as well.
Fixes #124
=> fix: login image not loading

bundles/uds-bundle.yaml, tasks.yaml
update uds-core while renovate PR is stuck with keyclaok v25 updates.
Fixes #
Relates to #
=> chore(deps): update uds core v0.24.0

src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/CustomAWSSAMLGroupMapper.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/CustomAWSSAMLGroupMapperTest.java
Add a check to the saml group mapper to restrict groups that use a `:` in the group name. Added a new test for checking this functionality as well.
Fixes #202
=> fix: restrict colon in group

renovate.json
The encryption in our renovate config is deprecated, the proper approach now is with creds in the portal (these are already setup).
Related to https://github.com/defenseunicorns/uds-identity-config/issues/10
=> chore: remove deprecated encryption on renovate config

src/realm.json, tasks.yaml
Modifies the trusted hosts policy to match `"*.${UDS_ADMIN_DOMAIN}"` instead of `"*.admin.${UDS_DOMAIN}"`. Note that `*.${UDS_DOMAIN}` will also match `*.admin.${UDS_DOMAIN}` due to how Keycloak interprets these. In some cases both list items may be identical, but Keycloak allows this without issue.
This should wait on the related PR in uds-core: https://github.com/defenseunicorns/uds-core/pull/1114
N/A
=> chore: add support for configurable admin domain

bundles/uds-bundle.yaml, docs/reference/UDS Core/IdAM/authentication-flows.md, tasks.yaml
Fixes the notes syntax for docs site.
N/A
=> docs: fix note syntax

src/theme/login/template.ftl
When enabling the admin ui to use a specific type of auth flow, there is a bug that doesnt show the correct client in the login theme. We've never ( add rarely will) use a custom theme for the admin ui however this will be value add with the new authentication configurations.
1. Modify the identity-config bundle to be only x509 enable auth flow
2. deploy identity-config with uds core  `uds run uds-core-integration-tests`
3. log into Admin UI
4. change login theme to be `Theme`
5. logout
6. verify that login page has change to the login theme and the title says `Admin Account` not `${client_security-admin-console}`
=> fix: admin ui login theme bug fix

.github/actions/renovate-readiness/action.yaml, .github/workflows/commitlint.yaml, .github/workflows/test.yaml
Not absolutely necessary since there is minimal renovate churn in the repo but to be as similar to uds-core possible.
=> chore: add action to check readiness on renovate PRs before running CI

.gitignore, tasks.yaml
Add Dev Docs task to identity-config
=> chore(docs): add dev docs task

src/test/cypress/cypress.config.ts
This Pull Request stabilizes tests that try to obtain `cy.document` object. Depending on the exact moment in the redirect flow, calling this may or may not end up with cross-origin call. These cross-origin calls end up with an error in Cypress 14 and the behavior will be permanently changed in Cypress 15 (see the [docs](https://docs.cypress.io/api/commands/origin)).
The easiest approach for the time-bing is to include the `injectDocumentDomain` option in the configuration. This ensures all calls to the `cy.document` pass regardless to the origin. A larger test restructure task has been scheduled in
#341
Fixes #338
=> chore: stabilize tests

docs/reference/UDS Core/IdAM/upgrading-versions.md, src/realm.json, src/test/cypress/realm.json
This Pull Request forces users to re-login after they change their credentials. 
More info: https://www.keycloak.org/docs/latest/release_notes/index.html#new-option-in-send-reset-email-to-force-a-login-after-reset-credentials
Since this is a low-priority hardening change, I skipped writing automated tests for it. 
Fixes #329
=> feat: force re-login after changing credentials

docs/reference/UDS Core/IdAM/upgrading-versions.md, src/realm.json, src/test/cypress/realm.json
Upstream Keycloak updates in 26.1.0 resulted in case sensitivity issues. This has caused applications that depend on these saml mappers to fail because the mapper was not correctly mapping to a keycloak attribute. 
Updated the realms to have lowercase naming conventions. Also added the saml mappers to the test realm for a follow on PR to UDS Core where a saml application will be added to tested apps.
=> fix: realm saml mappers

docs/reference/UDS Core/IdAM/uds-identity-config-overview.md
There has been some confusion about how the uds-identity-config is upgraded and what happens to existing keycloak realm configurations. this small change aims to address that.
=> chore(doc): add new section about upgrading identity config

.gitignore, src/test/cypress/cypress.config.ts, src/test/cypress/package-lock.json, src/test/cypress/package.json, tasks.yaml
It appears that in the latest version of cypress (14.1+) there was some optimizations made to the tests that has exposed a race condition that was undetected in the tests. ( could also be that the cypress tests are now synchronous by default whereas previous to the new cypress version they were asynchronous, however the release notes don't mention this).
The way that cypress manages injected CAC browser certs, means that it's there for all tests. Previously the registration test that actually uses that cert always got to it first, now the login user test gets there first and causes cypress to fail because it wasn't expecting to get a CAC pop up.
There is two avenues to fix this, i went with the 2nd option so that we could guarantee the outcome of tests now and in the future where there …
=> fix: broken cypress tests

src/realm.json, src/test/cypress/realm.json
In previous PR, renamed the authentication flows and this resulted in the doug user breaking because it depends on the authentication flow to disable the OTP. this resulted in OTP being present on playwright tests, which resulted in failures.
=> fix: rename auth flow

docs/reference/UDS Core/IdAM/authentication-flows.md, docs/reference/UDS Core/IdAM/customization.md, docs/reference/UDS Core/IdAM/uds-identity-config-overview.md
We’ve encountered issues in air-gapped environments where Keycloak’s X.509 authentication flow fails due to unreachable OCSP responders. Currently, there is no official documentation guiding users on how to configure Keycloak for such environments or what the trade-offs are between different options (fail-open vs. fail-closed, disabling OCSP, hosting an internal responder, etc.). We need clear guidance in the documentation for administrators who must configure Keycloak X.509 authentication in offline or restricted environments.
Fixes #412
=> chore(docs): update air gapped limitations for x509

tasks.yaml
New task introduced in 0.12.0 is called "setup" and causes maru errors because of duplicate task name that consumes this task file. Renaming to common-setup.
=> chore: rename task

docs/reference/UDS Core/IdAM/plugin.md, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/CustomGroupPathMapper.java, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/clientpolicy/executor/UDSClientPolicyPermissionsExecutor.java, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/clientpolicy/executor/UDSClientPolicyPermissionsExecutorConfiguration.java, src/plugin/src/main/java/com/defenseunicorns/uds/keycloak/plugin/clientpolicy/executor/UDSClientPolicyPermissionsExecutorFactory.java, src/plugin/src/test/java/com/defenseunicorns/uds/keycloak/plugin/clientpolicy/executor/UDSClientPolicyPermissionsExecutorTest.java, src/test/cypress/e2e/client-credentials.cy.ts, src/test/cypress/resources/test-package.yaml
This Pull Request introduces new configuration options for the `UDSClientPolicyPermissionsExecutor` that limit what the UDS Operator can do in Keycloak. 
Fixes: https://github.com/defenseunicorns/uds-identity-config/issues/385
=> feat: uds policy hardening

docs/reference/UDS Core/IdAM/truststore-customization.md
UDS Docs site doesn't like the use of `conf` as a type of code block. This fix removes a warning when building the site.
=> chore: small doc change

.github/workflows/commitlint.yaml
recently removed the labeled on action type from the commitlint and now it [doesnt run as expected](https://github.com/defenseunicorns/uds-identity-config/pull/455).
=> fix: commitlint action

README.md, docs/reference/UDS Core/IdAM/truststore-customization.md, tasks.yaml
The cacert task in this repo was not being used, except as consumed by uds-core. An updated task is being added to core in https://github.com/defenseunicorns/uds-core/pull/1567, and this PR changes the identity-config `cacert` task to explicitly focus on local dev builds of custom identity-config (specifically custom CAs).
Documentation was also updated to reference this task and explain usage.
N/A
=> chore: cleanup cacert tasks in identity-config

docs/reference/UDS Core/IdAM/customization.md
`values` is a YAML sequence (list/array). This PR updates the documentation to fix this YAML syntax error by changing the type from map to sequence in the customization docs example.
N/A
=> chore(docs): values is a YAML sequence

bundles/external-loadbalancer/uds-bundle.yaml, bundles/k3d-core-slim-dev/uds-bundle.yaml, bundles/theme-customizations/uds-bundle.yaml, src/test/cypress/e2e/group-authz.cy.ts, tasks.yaml
Remove unnecessary task to add group auth to Grafana.  Group auth is now added by default in core via: https://github.com/defenseunicorns/uds-core/pull/1809. Also bumps core references in bundles to `0.48.1` and updates the group auth tests.
Fixes #372
=> chore: remove grafana group auth task
